### ISSUE TITLE
Create links to CIViC variant records that are based on ClinGen Allele Registry

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-client#1008]
For example, for this variant:
https://civicdb.org/events/genes/58/summary/variants/1747/summary#variant

It would be awesome if you could get here by the variant's allele registry ID:
e.g. 

https://civicdb.org/links/allele/CA020450

This would link to:
http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/by_caid?caid=CA020450

**Comment by susannasiebert** [comment]
This has already been implemented (https://github.com/griffithlab/civic-server/pull/448). That PR been merged into staging but hasn't been made live yet. The link implemented in that PR is `civicdb.org/links/allele_registry/<allele registry id>` (e.g, `https://staging.civicdb.org/links/allele_registry/CA020450`).  I can change it to be `allele` if that's important.

**Comment by susannasiebert** [comment]
This feature has been deployed and the API docs have been updated.
