### ISSUE TITLE
VHL variant numbers don't make sense for "All variants" in display

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#1018]
<img width="437" alt="screen shot 2018-12-18 at 3 35 38 pm" src="https://user-images.githubusercontent.com/8527125/50184702-6d846f80-02db-11e9-8666-250c469e5f35.png">

"All variants" (the last option) should be more than "submitted and accepted variants" (the second option).

**Comment by jmcmichael** [comment]
Fix merged to staging, closing.
