### ISSUE TITLE
Wrong gene links when visiting through browse/evidence

### ISSUE THREAD

**Issue by billzt** [griffithlab/civic-client#1019]
Bug:

Visit https://civicdb.org/browse/evidence

Click into the first evidence (ID: 1421, FGFR1)

![tim 20181227114649](https://user-images.githubusercontent.com/1146090/50464663-2d08ae00-09cd-11e9-9697-4f5bb7937c7c.png)

Scroll up, the gene is not FGFR1, but  GJB5

![tim 20181227114842](https://user-images.githubusercontent.com/1146090/50464703-6e00c280-09cd-11e9-922f-d22f553669ea.png)

Maily because the link is wrong

**Comment by jmcmichael** [comment]
Fixed a couple deploys ago, closing.

**Comment by billzt** [comment]
Yeah, fixed! Thanks!
