### ISSUE TITLE
Add undo button to undo accepting/rejecting evidence item

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/civic-client#1035]
This button should only appear for a limited time (10 minutes, an hour) so that the evidence doesn't appear in any TSV dumps.

**Comment by jmcmichael** [comment]
Accept/Reject buttons replaced with an Undo button that will be displayed for 30 minutes after the time of the accept/reject action. This can be accomplished behind the scenes using the upcoming server feature that allows suggested changes for status.

**Comment by susannasiebert** [comment]
Other solutions are:
- Allowing users to reject an already accepted evidence items (#1036)
- Adding a confirmation pop up "are you sure" before an acceptance/rejection event gets submitted (#1239)
Closing #1036 and #1239 so that all the discussion can happen in one place on this issue.

**Comment by susannasiebert** [comment]
Closing in favor of #1036  for discussing the appropriate solution.
