### ISSUE TITLE
Allow people to reject an accepted evidence item

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/civic-client#1036]
The idea is to have an option when suggesting a change to an evidence item to be able to change the status from accepted to rejected. This could be achieved by making the status attribute of an evidence item editable and adding the existing "rejected" lifecycle event on the backend. Since this is just a suggested change, it already requires a comment and approval from an editor. The only accepted direction of status change is from accepted to rejected.

**Comment by susannasiebert** [comment]
This supersedes #929

**Comment by arpaddanos** [comment]
Same submittor/Acceptor (Cam)

2. - Idea: unaccept as an Editor function. 
3. - GitHub issue 1036 on client discussed this in the past. It states that a reject option should be available, but that does not cover the case of same submittor and acceptor. 
4. - Unaccept button or unaccept as a suggested change? The unaccept needs an accompanying explanation.
5. - Problem with submitted by: accpted by: on a submitted EID. an extra message on the EID when this state is detected can explain this state to users.
6. - Decision is to add unnacept to the Edit form. Only Editors can see this on the Edit form. It could be part of other edits
7. - What about rejected -> submitted funciton as part of this?
8. - Rejected to submitted seems unproblematic to add to this functionality

**Comment by susannasiebert** [comment]
During today's meeting it was decided to add the following functionality:
- When making a suggested change to an accepted or rejected evidence item, you will get the option to suggest a change to status. The drop down will contain the current status of the evidence item as well as `submitted`. This will effectively allow curators to suggest a change to an evidence item back to a submitted status.
- This will be available to both curators and editor (both curators and editors can suggest a change back to submitted status). Only editors can accept/reject the suggested change.

**Comment by susannasiebert** [comment]
Other solutions are:
- Adding an undo button (#1035)
- Adding a confirmation pop up "are you sure" before an acceptance/rejection event gets submitted (#1239)
Closing #1035 and #1239 so that all the discussion can happen in one place on this issue.

**Comment by susannasiebert** [comment]
We will need to ensure that once this is implemented the org and user stats calculations are updated not to count acceptance events if there are subsequent status events.

**Comment by jmcmichael** [comment]
As discussed, this feature will be initially implemented as a 'Revert to Submitted' button placed in the evidence settings popover that will change the item's status to Submitted from Accepted or Rejected. It will change the curation workflow as illustrated in the attached figure, and appear in the UI like the attached mockup:

![BGA-85_CIViC_curation-workflow_v1a](https://user-images.githubusercontent.com/132909/94847214-e76de600-03e7-11eb-83c7-850c6ae61911.png)
![BGA-85_revert-btn-mockup_v1a](https://user-images.githubusercontent.com/132909/94847225-ea68d680-03e7-11eb-9a74-af003771a8f7.png)
