### ISSUE TITLE
Advanced Search (Source) bugs

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#1042]
Pubmed ID no longer being shown. Duplicate entry being shown.
<img width="1229" alt="screen shot 2019-01-29 at 5 11 57 pm" src="https://user-images.githubusercontent.com/8527125/51947065-282e8400-23e9-11e9-9648-cbf31137a72b.png">

**Comment by kkrysiak** [comment]
Search link that provided the above result. https://civicdb.org/search/sources/8bb6d7e9-edee-4cf7-8fb9-19982612aeb3

**Comment by ahwagner** [comment]
Likely related: searches on PMIDs return 500 errors

![image](https://user-images.githubusercontent.com/811065/51991555-f4973c80-2470-11e9-922e-fc377c3b682d.png)

**Comment by jmcmichael** [comment]
Done.
