### ISSUE TITLE
PMID link out on evidence cards for assertions are broken

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#1044]
https://civicdb.org/events/assertions/6/summary
<img width="1224" alt="screen shot 2019-01-31 at 9 50 58 pm" src="https://user-images.githubusercontent.com/8527125/52101693-6e7b1300-25a2-11e9-932d-443c8ab474f1.png">
Totally fine in the main evidence view. https://civicdb.org/events/genes/19/summary/variants/33/summary/evidence/982/summary#evidence

**Comment by jmcmichael** [comment]
Done.
