### ISSUE TITLE
Advanced Search Requests for Source

### ISSUE THREAD

**Issue by arpaddanos** [griffithlab/civic-client#1045]
When searching using source, "Search Sources", it would be nice if one of the columns was number of EIDs associated to that source.

**Comment by susannasiebert** [comment]
This is already a feature. The search field for this is "Evidence Items":
![untitled 2](https://user-images.githubusercontent.com/6617192/52153267-f6aef600-263e-11e9-8f0b-9ac0936c1b96.png)

**Comment by susannasiebert** [comment]
Just realized that I misread your request. Are you talking about adding that as a column to the results table?

**Comment by arpaddanos** [comment]
Yes, results table from Search Sources, so we can quickly see and sort on how many EIDs a source has
