### ISSUE TITLE
Advanced search by Pubmed ID is broken

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#1049]
Presumably due to the asco/pubmed change?
<img width="1207" alt="screen shot 2019-02-09 at 10 36 09 pm" src="https://user-images.githubusercontent.com/8527125/52529648-24d5ab00-2cbb-11e9-9f30-308fa1056279.png">

**Comment by tmooney** [comment]
This looks like what griffithlab/civic-server#484 is meant to address.

**Comment by kkrysiak** [comment]
You are right. I missed that. I forgot Alex had added the advanced search issue to my other one. Thanks @tmooney!
