### ISSUE TITLE
create group stats endpoint

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/civic-client#1071]
Add a /stats/groups endpoint that includes things like: 

* group count (already part of the community stats response)
* activities per group (evidence added, changes requested, etc.)
* badges per group?

**Comment by susannasiebert** [comment]
Are you imaging this to be limited to just groups, i.e. organizations that have a parent? Any reason why this couldn't just get rolled into the existing `/stats/community` endpoint?

**Comment by jmcmichael** [comment]
Yeah I think that would be a better location for it.

**Comment by jmcmichael** [comment]
This issue enables implementation of #788.
