### ISSUE TITLE
Add linkout to FDA companion tests

### ISSUE THREAD

**Issue by acoffman** [griffithlab/civic-client#1080]
This should be an option when "yes" is clicked on the assertion.

Sample IDs in the right column here: https://www.fda.gov/MedicalDevices/ProductsandMedicalProcedures/InVitroDiagnostics/ucm330711.htm

**Comment by susannasiebert** [comment]
I assume we'd also want to link out to the companion page. The URL differs depending on what stage of approval the companion test is in.  We could try to infer the type from the ID prefix, or record it in a separate field. Thoughts?

**Comment by susannasiebert** [comment]
This is actually a duplicate for #998. Closing.
