### ISSUE TITLE
Add Allele registry ID to variant data dumps

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-client#1086]
In general I think we should revisit the contents of the variants data dump.  Are there other values that could be added?

**Comment by susannasiebert** [comment]
Other fields to add:
- ClinVar ID
- Aliases
- Linked assertions (ids and urls)

Rename civic actionability score to whatever we named it

**Comment by susannasiebert** [comment]
PR #501 has been updated to add the additional columns and rename the score column.
