### ISSUE TITLE
Evidence grid filtering lacks Predisposing clinical significance values

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#1120]
<img width="1254" alt="Screen Shot 2019-06-20 at 2 18 06 PM" src="https://user-images.githubusercontent.com/8527125/59875458-6ca1c880-9366-11e9-8c48-81bd95c46fc5.png">

I would expect that Pathogenic, Likely Pathogenic, Uncertain Significance, Likely Benign, and Benign would be in this list.

**Comment by susannasiebert** [comment]
This is not needed anymore since #1121 has been implemented.
