### ISSUE TITLE
Change Clinical Significance and Evidence Direction for Predisposing Evidence Items to 'N/A'

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/civic-client#1121]
Users tend to see VUS, benign, etc. and think of it as an assertion instead of a single piece of evidence.  As soon as they see that, they assume it is the final assertion. It would better to say “N/A” or “Positive/Negative” or “Undetermined” or something else for Clinical Significance of the evidence item.  Then use the ACMG category at the Assertion level.  We could add the ability to store individual ACMG evidence codes (PVS1, PM1, …) for individual evidence records for predisposing evidence.

We decided:
- Evidence Codes should be added to the Evidence Statement
- Evidence Direction and Clinical Significance for Predisposing should be ‘N/A’
- Change all existing evidence items to be ‘N/A’ Evidence Direction and Clinical Significance
- Suggested Revisions are a problem. They would cause an error if the old field as changed under the hood but editors should just reject all suggested revisions that involve predisposing clinical significance and/or evidence direction
- Future desire: Add a separate field for Evidence Codes on predisposing evidence items

**Comment by susannasiebert** [comment]
We original implemented the existing list of clinical significance terms in https://github.com/griffithlab/civic-server/issues/255

**Comment by kkrysiak** [comment]
This change has been made in response to conversations with the ClinGen group. Initially we utilized pos/neg but this also caused confusion, see https://github.com/griffithlab/civic-server/issues/255.

**Comment by susannasiebert** [comment]
The following predisposing evidence items have outstanding suggested changes to their clinical significance field and should be resolved before this change is implemented:
[4925, 1872, 1871, 4902, 4953, 1944, 4938, 6442, 4925, 7160]

**Comment by obigriffith** [comment]
These have been resolved. They were all sensible revisions (albeit under our old scheme for predisposing evidence). I accepted most of them, even if in some cases their clinical significance will now be deprecated.

**Comment by kkrysiak** [comment]
@arpaddanos, @acoffman and I discussed and suggested we make suggested changes submitted by civicbot that can then be moderated. Otherwise, these are clobbered in the interface with no obvious reason why this happened. Unilateral CIViC change is the reason.

**Comment by arpaddanos** [comment]
The CIViC Bot will submit suggested change to previous predisposing EIDs. It will suggest changes to Clinical Significance and Evidence Direction (NA to both). Editors will have to follow a protocol for dealing with these changes. **Moderation Protocol** should include updating Evidence Statement to reflect original intent of submittor, with that original intent reflected not in a Clinical Significance but now in the form of ACMG codes and also possibly a sentence in the Evidence Statement. (i.e. Authors considered this as evidence for variant pathogenicity). Evidence statement should be updated to follow SOP guidelines: **a summary of predisposing information reported in the Evidence Source followed by a listing of ACMG codes, each with a brief justification for its inclusion**.

**Comment by arpaddanos** [comment]
We have decided to reopen issue to run it by Griffiths and to run the suggested **moderation protocol** outlined above.

**Comment by susannasiebert** [comment]
We also need to ensure that the filtering dropdowns in various evidence and assertion grids need to be updated so that the correct clinical significance options for evidence items and assertions are displayed.

Edit: This will be tackled in issue https://github.com/griffithlab/civic-client/issues/1282

**Comment by susannasiebert** [comment]
Right now the assertion form also was updated to only allow `N/A`. This should be changed back to support all predisposing clinical significance options.
