### ISSUE TITLE
Problematic ClinGen Allele Registry IDs of the form "_:CA"

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-client#1131]
In the current nightly dump I see 34 variants with ClinGen Allele Registry IDs that look like this: "_:CA"

They seem to be mostly insertions and deletions indicating a possible parsing issue:

Here are the problematic examples:

variant_id | variant_civic_url | gene | chromosome | start | stop | reference_bases | variant_bases | variant_types | hgvs_expressions | last_review_date | civic_variant_evidence_score | allele_registry_id
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
522 | https://civic.genome.wustl.edu/links/variants/522 | BRAF | 7 | 140477838 | 140477855 | AGGTGCTGTCACATTCAA | inframe_deletion | ENST00000288602.6:c.1453_1470del | 2018-11-30 14:43:18 UTC | 3 | _:CA
581 | https://civic.genome.wustl.edu/links/variants/581 | BRAF | 7 | 140477859 | 140477860 | TT | CA | loss_of_function_variant,missense_variant | NC_000007.13:g.140477859_140477860delinsCA,ENST00000288602.6:c.1448_1449delinsTG | 2018-11-30 14:43:27 UTC | 0.75 | _:CA
615 | https://civic.genome.wustl.edu/links/variants/615 | JAK2 | 9 | 5070053 | 5070054 |   | G |   | NC_000009.11:g.5070053_5070054insG | 2018-11-30 14:44:15 UTC | 10 | _:CA
638 | https://civic.genome.wustl.edu/links/variants/638 | RB1 | 13 | 49033946 | 49033947 |   | A | frameshift_truncation | ENST00000267163.4:c.2083_2084insA,NC_000013.10:g.49033946_49033947insA | 2018-11-30 14:43:34 UTC | 2 | _:CA
655 | https://civic.genome.wustl.edu/links/variants/655 | MAP2K1 | 15 | 66727449 | 66727463 | CCAGAAGCAGAAGGT | inframe_deletion | ENST00000307102.5:c.165_179del,NC_000015.9:g.66727449_66727463del | 2018-11-30 14:43:34 UTC | 10 | _:CA
728 | https://civic.genome.wustl.edu/links/variants/728 | MLH1 | 3 | 37081718 | 37081719 | GT | AG | missense_variant | ENST00000231790.2:c.1600_1601delinsAG,NC_000003.11:g.37081718_37081719delinsAG | 2018-11-30 14:43:37 UTC | 0.25 | _:CA
729 | https://civic.genome.wustl.edu/links/variants/729 | UGT1A1 | 2 | 234668881 | 234668882 |   | TATATATATATATA | microsatellite | NC_000002.11:g.234668881_234668882TA[7] | 2018-11-30 14:43:43 UTC | 50 | _:CA
730 | https://civic.genome.wustl.edu/links/variants/730 | MLH1 | 3 | 37089094 | 37089095 | GG |   | frameshift_truncation | ENST00000231790.2:c.1816_1817delGG,NC_000003.11:g.37089094_37089095del | 2018-11-30 14:43:37 UTC | 0.5 | _:CA
744 | https://civic.genome.wustl.edu/links/variants/744 | MLH1 | 3 | 37067365 | 37067365 | C |   | frameshift_truncation | ENST00000231790.2:c.1276delC,NC_000003.11:g.37067365del | 2018-11-30 14:43:38 UTC | 0.5 | _:CA
746 | https://civic.genome.wustl.edu/links/variants/746 | MLH1 | 3 | 37090406 | 37090406 | C |   | frameshift_truncation | NC_000003.11:g.37090406del,ENST00000231790.2:c.2001del | 2018-11-30 14:43:38 UTC | 0.5 | _:CA
750 | https://civic.genome.wustl.edu/links/variants/750 | MLH1 | 3 | 37053551 | 37053551 | T |   | frameshift_truncation | ENST00000231790.2:c.638delT,NC_000003.11:g.37053551del | 2018-11-30 14:43:39 UTC | 0.5 | _:CA
756 | https://civic.genome.wustl.edu/links/variants/756 | MLH1 | 3 | 37081726 | 37081726 | T |   | frameshift_truncation | NC_000003.11:g.37081726del,ENST00000231790.2:c.1608del | 2018-11-30 14:43:40 UTC | 0.5 | _:CA
762 | https://civic.genome.wustl.edu/links/variants/762 | MSH2 | 2 | 47641433 | 47641433 | T |   | frameshift_variant | ENST00000233146.2:c.818delT,NC_000002.11:g.47641433del | 2018-11-30 14:43:54 UTC | 0.5 | _:CA
763 | https://civic.genome.wustl.edu/links/variants/763 | MSH2 | 2 | 47630413 | 47630414 |   | G | frameshift_elongation | NC_000002.11:g.47630414dupG | 2018-11-30 14:43:40 UTC | 0.5 | _:CA
765 | https://civic.genome.wustl.edu/links/variants/765 | MSH6 | 2 | 48027794 | 48027795 | TC |   | frameshift_truncation | ENST00000234420.5:c.2672_2673delTC,NC_000002.11:g.48027794_48027795del | 2018-11-30 14:43:44 UTC | 0.5 | _:CA
816 | https://civic.genome.wustl.edu/links/variants/816 | ERBB2 | 17 | 37880997 | 37880998 | GG | CT | missense_variant | ENST00000269571.5:c.2326_2327delinsCT | 2018-11-30 14:43:46 UTC | 7.5 | _:CA
960 | https://civic.genome.wustl.edu/links/variants/960 | KIT | 4 | 55593603 | 55593604 | TG | AC | missense_variant | ENST00000288135.5:c.1669_1670delinsAC,NC_000004.11:g.55593603_55593604delinsAC | 2018-11-30 14:43:56 UTC | 0 | _:CA
1305 | https://civic.genome.wustl.edu/links/variants/1305 | ERBB2 | 17 | 37881064 | 37881065 | CA | TG | missense_variant | ENST00000269571.5:c.2393_2394delCAinsTG,NC_000017.10:g.37881064_37881065delinsTG | 2018-11-30 14:43:59 UTC | 0 | _:CA
1539 | https://civic.genome.wustl.edu/links/variants/1539 | PDGFRA | 4 | 55141029 | 55141034 | TGGAGG |   | inframe_deletion |   | 2018-11-30 14:44:26 UTC | 0 | _:CA
1557 | https://civic.genome.wustl.edu/links/variants/1557 | ERBB2 | 17 | 37880999 | 37881000 |   | TGT | inframe_insertion |   | 2018-11-30 14:44:19 UTC | 0 | _:CA
1558 | https://civic.genome.wustl.edu/links/variants/1558 | KIT | 4 | 55592182 | 55592183 |   | GCCTAT | inframe_insertion |   | 2019-07-09 22:06:40 UTC | 7 | _:CA
1639 | https://civic.genome.wustl.edu/links/variants/1639 | ABL1 | 9 | 133753954 | 133755455 | TG | GT | splice_donor_variant | ENST00000318560.5:c.1423_1424delinsGT | 2019-03-12 00:37:07 UTC | 5 | _:CA
1657 | https://civic.genome.wustl.edu/links/variants/1657 | ABL1 | 9 | 133748300 | 133748301 | GG | CT | coding_sequence_variant |   | 2019-03-12 01:18:55 UTC | 3 | _:CA
1912 | https://civic.genome.wustl.edu/links/variants/1912 | VHL | 3 | 10183754 | 10183755 |   | T | frameshift_truncation | NC_000003.11:g.10183755dupT,NM_000551.3:c.224dupT,NP_000542.1:p.F76Lfs*56 | 2019-07-03 16:24:28 UTC | 7.5 | _:CA
2135 | https://civic.genome.wustl.edu/links/variants/2135 | VHL | 3 | 10188226 | 10188232 | GACACAC |   | frameshift_variant | ENST00000256474.2:c.369_375delGACACAC | 2018-11-30 14:45:09 UTC | 0 | _:CA
2138 | https://civic.genome.wustl.edu/links/variants/2138 | VHL | 3 | 10191532 | 10191532 | C |   | frameshift_truncation | ENST00000256474.2:c.525delC | 2018-11-30 14:44:51 UTC | 7.5 | _:CA
2141 | https://civic.genome.wustl.edu/links/variants/2141 | VHL | 3 | 10191596 | 10191596 | G |   | frameshift_truncation | ENST00000256474.2:c.589delG | 2018-11-30 14:45:17 UTC | 10 | _:CA
2329 | https://civic.genome.wustl.edu/links/variants/2329 | VHL | 3 | 10191622 | 10191622 | C |   | frameshift_truncation | ENST00000256474.2:c.615delC | 2019-03-23 00:00:06 UTC | 0 | _:CA
2432 | https://civic.genome.wustl.edu/links/variants/2432 | VHL | 3 | 10183790 | 10183791 |   | A | frameshift_elongation | ENST00000256474.2:c.259_260insA | 2019-03-23 00:00:07 UTC | 0 | _:CA
2489 | https://civic.genome.wustl.edu/links/variants/2489 | VHL | 3 | 10191648 | 10191649 |   | C | stop_lost | ENST00000256474.2:c.641_642insC | 2019-03-22 00:00:07 UTC | 0 | _:CA
2510 | https://civic.genome.wustl.edu/links/variants/2510 | VHL | 3 | 10183735 | 10183736 |   | G | frameshift_variant | ENST00000256474.2:c.204_205insG | 2019-03-23 00:00:11 UTC | 0 | _:CA
2511 | https://civic.genome.wustl.edu/links/variants/2511 | VHL | 3 | 10183770 | 10183770 | G |   | frameshift_truncation | ENST00000256474.2:c.239delG | 2019-03-23 00:00:08 UTC | 0 | _:CA
2512 | https://civic.genome.wustl.edu/links/variants/2512 | VHL | 3 | 10183770 | 10183776 | GTCCGCG |   | frameshift_truncation | ENST00000256474.2:c.239_245delGTCCGCG | 2019-03-23 00:00:11 UTC | 0 | _:CA
2517 | https://civic.genome.wustl.edu/links/variants/2517 | VHL | 3 | 10183863 | 10183863 | G |   | frameshift_truncation | ENST00000256474.2:c.332delG | 2019-03-23 00:00:08 UTC | 0 | _:CA

**Comment by susannasiebert** [comment]
I can confirm that this problem persists on the allele registry side for some of the variants in this list, but not all. Some (e.g. 728) now resolve to an actual ID. Others (e.g. 2517) now return nil, as expected. One variant where this persists is 2141 where the HGVS string is `NC_000003.11:g.10191596del`. The API response is:
```
{"@context"=>"http://reg.genome.network/schema/allele.jsonld",
 "@id"=>"_:CA",
 "genomicAlleles"=>
  [{"chromosome"=>"3",
    "coordinates"=>
     [{"allele"=>"", "end"=>10149912, "referenceAllele"=>"G", "start"=>10149911}],
    "hgvs"=>["NC_000003.12:g.10149912del", "CM000665.2:g.10149912del"],
    "referenceGenome"=>"GRCh38",
    "referenceSequence"=>"http://reg.genome.network/refseq/RS000051"},
   {"chromosome"=>"3",
    "coordinates"=>
     [{"allele"=>"", "end"=>10191596, "referenceAllele"=>"G", "start"=>10191595}],
    "hgvs"=>["NC_000003.11:g.10191596del", "CM000665.1:g.10191596del"],
    "referenceGenome"=>"GRCh37",
    "referenceSequence"=>"http://reg.genome.network/refseq/RS000027"},
   {"chromosome"=>"3",
    "coordinates"=>
     [{"allele"=>"", "end"=>10166596, "referenceAllele"=>"G", "start"=>10166595}],
    "hgvs"=>["NC_000003.10:g.10166596del"],
    "referenceGenome"=>"NCBI36",
    "referenceSequence"=>"http://reg.genome.network/refseq/RS000003"},
   {"coordinates"=>
     [{"allele"=>"", "end"=>13278, "referenceAllele"=>"G", "start"=>13277}],
```
note the ` "@id"=>"_:CA",`.
We will need to handle cases where this is the return value and fix the database.

**Comment by malachig** [comment]
I have a guess as to what is going on here.  In your example, if you go to the UI and query for:
NC_000003.11:g.10191596del

http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/allele?hgvs=NC_000003.11%3Ag.10191596del

Note the `This allele is not present in the allele registry. To get CA identifier, please click on the "Get CA identifier" below.` at the top of the page.

This means the HGVS allele format is understood by ClinGen Allele Registry.  But no one has registered this specific allele yet.

If this is the case, the actions items seem to be:
1.) Register these alleles in the registry
2.) Come up with a more intuitive way of handling unregistered alleles so that it is more obvious the the CIViC curator that they need to go and do the registration...

**Comment by malachig** [comment]
Screenshots of this example variant before the allele is registered:

<img width="703" alt="api response" src="https://user-images.githubusercontent.com/856728/61085120-22f04f00-a3f5-11e9-9b5f-110ea133ad0c.png">

<img width="1183" alt="ui view" src="https://user-images.githubusercontent.com/856728/61085121-2388e580-a3f5-11e9-88c0-3656120f8103.png">

**Comment by malachig** [comment]
Now the screenshots for the same variant but after I have registered the allele with ClinGen Allele Registry:

<img width="689" alt="api response after" src="https://user-images.githubusercontent.com/856728/61085286-782c6080-a3f5-11e9-8e12-79082a309d8c.png">

<img width="1181" alt="ui view after" src="https://user-images.githubusercontent.com/856728/61085287-782c6080-a3f5-11e9-87a5-f1c28d03bb21.png">

**Comment by malachig** [comment]
Seems to confirm my theory.  In conclusion it would be faithful to the ClinGen Allele Registry API response to display `_:CA`.  But this is a bit unintuitive to the end user, in particular because it appears in our TSV dumps but is not displayed in the CIViC UI.

**Comment by malachig** [comment]
It would be amazing if when this response is observed, in CIViC we should say something like Allele Not Registered.  Even better with a link to go register it.

**Comment by malachig** [comment]
Another question I have relating to this issue is, what happens in an allele gets registered?  Are the Allele Registry IDs we get back from ClinGen periodically updated?  Or once we have received `_:CA` will that remain in our database forever?

**Comment by malachig** [comment]
I went through all the `_:CA` cases and where possible registered missing allele with the ClinGen Allele Registry.  There were a few I could not resolve.  If we update the database now hopefully any remaining issues will be more obvious.  We still need to deal with how to handle this case which will be ongoing.  There will always be the possibility of encountering an allele that is not yet registered in ClinGen but needs to be.

**Comment by susannasiebert** [comment]
Right now we don't update the allele registry ID in our database although there is code already merged into staging that will change that behavior (from https://github.com/griffithlab/civic-server/pull/511) and check weekly whether variants with an allele registry id in our database have any changes to that id. That would catch this case, I believe.

In terms of how to handle these cases with `_:CA` we can either update the behavior of the scraper and treat them as nil. If we do this we would lose the information that this variant _could_ be registered. If we keep the current behavior we would need some changes on the frontend to implement the desired behavior of having the link to register the variant. @jmcmichael how complicated would this be?

**Comment by malachig** [comment]
Even if it just displayed `_:CA` that would be helpful now that we understand what is going on.  Better still would be to convert this to a message saying `Allele not yet registered` that linked you to the appropriate page to register it.

**Comment by jmcmichael** [comment]
I've updated the variant summary to show _:CA allele 'ids', and added a tooltip reading 'Allele not registered with ClinGen.' _:CA is linked to [the ClinGen Allele Registry landing page)[http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/landing].

![Screenshot 2019-07-23 12 15 16](https://user-images.githubusercontent.com/132909/61732604-907c7380-ad43-11e9-844d-e5dd8a525726.png)

Ideally, clicking on '_:CA' would load a clingen allele registery form, but according to [the instructions](http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/landing) (click the 'Learn More' button), one needs to first email someone at a gmail address to get a user/pass and then I guess they'll send you a link to the form. 

We could provide more info in the tooltip - 'Allele not registered, please sign up with ClinGen to register it!', but it seems odd to include bureaucratic procedures for other knowledgebases into the UI code.
