### ISSUE TITLE
add evidence variant field should warn users if an unfamiliar variant is entered

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/civic-client#204]

**Comment by jmcmichael** [comment]
This should be implemented as a notice under the field if the user enters a variant name not included in the typeahead results from the server. Something like 'This appears to be a new variant name, please ensure your contribution is a valid variant'.

**Comment by lsheta** [comment]
When adding evidence under a particular gene, could the drop down of variants only include variants specific to that gene?
