### ISSUE TITLE
approve/reject evidence item needs more feedback on frontend

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/civic-client#259]

**Comment by malachig** [comment]
@jmcmichael does this refer to what happens when you press the `Accept` or `Reject` button on a new evidence item?  I have been reviewing many new evidence items and currently nothing happens when you press the `Accept` button.  Have to do a page reload to continue working on that evidence item.

**Comment by jmcmichael** [comment]
Yeah, I'm going to add a 'Item Accepted/Rejected' message, and make sure any UI elements are updated accordingly. I'll make sure this gets fixed before the next deploy.

**Comment by malachig** [comment]
Perhaps related to this, in the live site, if you reject an revision, the `Accept`/`Reject` buttons remain visible even after a page reload.

**Comment by jmcmichael** [comment]
Implemented.
