### ISSUE TITLE
Provide disease ontology synonyms as searchable items in add evidence page

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#266]
Disease ontology does have a notion of synonyms for any given disease entry. Is that something we can get from their API to use for searching disease names in the add evidence page? Functionality would be similar to that observed when searching gene aliases from the main search box. But the first question is whether this would be possible to get in the first place. We should also discuss whether to restrict to only [exact] synonyms or include [related] synonyms as well (and whether that information is provided).

**Comment by jmcmichael** [comment]
Disease field's typeahead component now searches shows matches to disease ontology aliases.
