### ISSUE TITLE
Revision text displaying strangely?

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-client#309]
It seems like some revisions are being broken down into multiple insertions/deletions in the review view.  For example:
https://civic.genome.wustl.edu/#/events/genes/1885/talk/revisions/list/481/summary#gene

Perhaps this happens in the curator enters new lines in their edit?

![screen shot 2015-12-28 at 1 13 24 pm](https://cloud.githubusercontent.com/assets/856728/12023988/f5d367bc-ad64-11e5-91b6-7a177b104721.png)

**Comment by jmcmichael** [comment]
I'm not sure but I think that this is the result of pasting in a new description w/ unusual characters between sentences. The client just shows what the server provides, and we don't have much control over how the server generates these diffs. If this crops up again, and we have an example that we can reproduce we can dig further into the reason why this occurs.
