### ISSUE TITLE
Must refresh page after a variant is renamed to get all occurrences on the page to update

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-client#323]
If you rename a variant and submit the change, then approve the revision, the variant name updates in the list of variants on the left side of the page.  

However, it does not update in the headers of the section below:
$Variant_Name Revisions
$Variant_Name Comments
$Variant_Name Log

These maintain the old name until a page reload.

**Comment by jmcmichael** [comment]
Fixed.
