### ISSUE TITLE
Add two basic site/curation stats to the landing page

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-client#330]
It would be great if on the landing page, perhaps at the bottom of the current statistics section we could have two stats that tell you the state of review by site editors:

1.) # of new evidence statement awaiting review
2.) # of revisions (all types) awaiting review

These two numbers give you an idea of how much work the editorial team has to do and act as yet another reminder that new things are being considered for addition right now.

**Comment by acoffman** [comment]
I can add these counts to the stats endpoint used to populate that section of the page. Should be pretty easy!

**Comment by kkrysiak** [comment]
The one thing I don't like about it is that it is a reminder of the backlog we are currently suffering. It's kind of the data submission issue where if it takes 3 months for us to actually review your entry, I could see it as a deterrent to being adding your content. Just a thought.

**Comment by malachig** [comment]
This is actually why I want to shine light on the current status.  If we have a backlog, we should own that...  Right now, you will be able to see that yes there are 123 evidence statements awaiting acceptance.  But this is of 839 total right now.  This has come down a lot. 

Whether we draw attention to it or not, we need to keep on top of the reviewing...

**Comment by obigriffith** [comment]
Yeah. I agree. Normally on a website you avoid drawing attention to any hint of staleness. But, in this case, the whole premise of CIViC is to stay current. Drawing attention to outstanding revisions should help motivate us to stay on top of it. In this case, this is a very good problem to have.

**Comment by kkrysiak** [comment]
I see your point and it is a good problem to have. I absolutely agree we need to stay on top of it, not sure I need a reminder to get me to do that.

**Comment by kkrysiak** [comment]
Another possibility would be to add this to the curator page. Related to https://github.com/genome/civic-client/issues/580

**Comment by acoffman** [comment]
This is ready to go on the server side!

**Comment by malachig** [comment]
I think the stats page now partially addresses this issue in that you can see how many evidence records have a `Submitted` status:
https://civicdb.org/statistics/evidence

The rest of this issue could be resolved by just adding another pie chart on that page that shows evidence records with pending revisions vs. those that do not.

**Comment by jmcmichael** [comment]
Created #1077 to replace this issue. Closing.
