### ISSUE TITLE
must reload page after resolving an outstanding revision to get ! symbol to disappear 

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-client#441]
When reviewing a revision to an evidence record, I hit the `Accept Revision` button. The page partially updates, removing the buttons, and noting a new review by my user, but the `!` icon remains until I force a reload of the page.

**Comment by obigriffith** [comment]
It looks like this has been fixed. However, I believe the reverse problem now (still?) exists. I.e., when I propose a revision and hit submit, the page reloads and I see my revision in the grid but I have to refresh to get the ! to reappear.

**Comment by yanyangfeng** [comment]
Missed that when I was working on the original issue - just submitted a pull request to fix this

**Comment by kkrysiak** [comment]
Hopefully this is the right place to put this. Although the ! on the variant disappears after accepting a revision, it does not for the variant group as well. After a refresh the variant group ! will disappear but it does require a refresh.

<img width="793" alt="screen shot 2017-04-02 at 11 00 58 am" src="https://cloud.githubusercontent.com/assets/8527125/24588315/f626c304-1793-11e7-9cc8-0a01948a0d99.png">

**Comment by yanyangfeng** [comment]
PR #713 should fix this.

**Comment by kkrysiak** [comment]
I'm still noticing this behavior. Are we just waiting on a deploy for this?

**Comment by acoffman** [comment]
Hrm, we've certainly deployed since this has been merged. @yanyangfeng, do you know of any edge cases that this fix may not have caught?

**Comment by kkrysiak** [comment]
I was working on KRAS variant suggested revisions.

**Comment by jmcmichael** [comment]
I refactored @yanyangfeng's PR, I may have missed a test case, I'll see what's up.

**Comment by jmcmichael** [comment]
Just pushed a fix to master, closing.
