### ISSUE TITLE
editors should be allowed to edit evidence item's variant and gene links

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/civic-client#514]
Should be just as simple as adding a Gene field to the edit Variant form, and a Variant field to the edit Evidence form.

Editors should also be able to specify new genes and variants. Users should be warned if they are creating a new gene/variant, or use a UI similar to the drug typeahead/ create new drug ui on the AddEvidence form.

**Comment by susannasiebert** [comment]
This is a duplicate to #783. Closing.
