### ISSUE TITLE
What is the expected and desired behavoir of variants with only rejected evidence in variant groups?

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#535]
I just accepted the addition of other variants to the BRAF fusion variant group. One of these still has a pending EID. While I anticipate this will be accepted, I wonder what will happen if it was not.

I think the desired response will be that it is not displayed under the variant group until it has accepted evidence.

**Comment by jmcmichael** [comment]
Currently, a variant group will be shown if it contains an evidence item with only rejected evidence. #1005 deals with this, and i've added it to the 1.6 category as I'll need to include the show/hide variant group logic in with the logic that shows/hides evidence of various categories.
