### ISSUE TITLE
publication queue 'clear all filters' prevents going back to filtered

### ISSUE THREAD

**Issue by obigriffith** [griffithlab/civic-client#586]
Toggling the 'show curated' and 'show rejected' sources works (although the toggle status is not that intuitive) until the 'clear all filters' is selected. After that toggling the other two buttons can't get you back to a filtered state and only a browser 
![screenshot 2016-11-13 18 48 41](https://cloud.githubusercontent.com/assets/1638042/20249925/4003f738-a9d2-11e6-85f3-e6fda46ae757.png)
refresh helps.

**Comment by jmcmichael** [comment]
The UI-Grid team intends to release a major version soon that changes the grid menu API, and may fix this bug: https://github.com/angular-ui/ui-grid/issues/4657 - I'll wait until then to fix this behavior. Unfortunately this menu item is non-trivial to hide.

**Comment by jmcmichael** [comment]
Ui-grid updates appear to have solved the problem, I am able to toggle Rejected/Curated then Clear, and subsequent Rejected/Curated toggles re-filter the grid as expected. Closing.
