### ISSUE TITLE
Unable to Submit Revisions to ABCB1 S893A/T

### ISSUE THREAD

**Issue by KujanL** [griffithlab/civic-client#592]
I tried to submit a revision to this variant and an error comes up. I then tried to complete other submissions as a test and it worked (no error). So the problem I believe lies with this variant alone. 
![screen shot 2016-11-24 at 12 34 15 pm](https://cloud.githubusercontent.com/assets/15361912/20608039/553f7522-b243-11e6-8bc8-7df945accc8f.png)

**Comment by acoffman** [comment]
What fields were you attempting to modify? Did it happen to be PubMed ID for sources?

The error I'm seeing is that we attempt to fetch pubmed data and pubmed claims the id isn't valid. Sometimes this can happen if their API just isn't working temporarily as well. Either way we should handle this error case more gracefully!

**Comment by KujanL** [comment]
Yes. I was trying to submit an alias for this variant with a url source: https://www.pharmgkb.org/rsid/rs2032582 

I tried to enter it once again just now and the same error occurred.

**Comment by jmcmichael** [comment]
I was able to complete a suggested change to this variant on my local development install.

The updated pubmed fields will show an 'Error fetching source' message in the citation blank, so the UI is doing a bit better job at providing feedback if this happens.

Closing.
