### ISSUE TITLE
Hyperlinks not working properly in gene descriptions

### ISSUE THREAD

**Issue by dandanxu** [griffithlab/civic-client#597]
![image](https://cloud.githubusercontent.com/assets/4357327/20806823/67db462a-b7ca-11e6-8eb1-dd8f7ee8a452.png)
See https://civic.genome.wustl.edu/#/events/genes/6/summary/variants/397/summary
the link to FLOSSIES

**Comment by susannasiebert** [comment]
This is not a functionality we plan to support.
