### ISSUE TITLE
Support 'sources' for Variant Groups. 

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#609]
Currently no sources can be added to Variant Group summaries. This would be nice to have like we do for Variant and Gene Summaries.

**Comment by arpaddanos** [comment]
I would also suggest one avenue for expansion of variant group functionality is to allow variant groups to accept EIDs.

**Comment by kkrysiak** [comment]
That is a much bigger change. @arpaddanos please add another issue for this. Sources are already supported and a very minor field to add to variant groups. Evidence grids would be a much bigger thing.
