### ISSUE TITLE
Update "citing CIViC" FAQ entry with link to publication

### ISSUE THREAD

**Issue by acoffman** [griffithlab/civic-client#616]

**Comment by malachig** [comment]
Currently we link to the Bioarxiv version of the manuscript.  Update this as soon as the paper comes out.  Also, we should add a link to the citation in a few other places as well.  

- Perhaps the `About` page? 
- We should update the link on the Introduction help page as well.

**Comment by malachig** [comment]
Bumping this.  Now that the paper is out we should update or add the final citation throughout the paper.  We should link to the full paper in Nature Genetics and PubMed record:
http://dx.doi.org/10.1038/ng.3774
https://www.ncbi.nlm.nih.gov/pubmed/28138153

This should go on the help page, about page, FAQ page, and perhaps even on the landing page?

**Comment by kkrysiak** [comment]
This is done.
