### ISSUE TITLE
add 'suggested change exist' exclamation point to variant tag labels

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/civic-client#631]
In the variant menu, each tag label should show an exclamation point if pending suggested changes exist, in the same manner as shown in entity tabs.

**Comment by yanyangfeng** [comment]
so is the idea here to show the exclamation if there are any revisions pending for the variant or evidence items associated with the variant?

**Comment by jmcmichael** [comment]
Just pending revisions for the variant it appears next to. However, the server will need to add revision information to the records returned from the /genes/:geneId/variants endpoint, as it currently does not provide it.

**Comment by malachig** [comment]
I think both would be ideal.  

When I visit a gene page as a consumer this would give a high level view of where things are currently under revision.  

When I visit as an editor I would know where my attention is needed.  Currently I have to click on every variant in turn to see that, or use the admin interface, or conduct two advanced queries (one for evidence, one for variants).  Having to leave the page to find these things really disrupts the flow for an editor thinking about the variants and evidence for a gene.

**Comment by jmcmichael** [comment]
Sure, that makes sense. However, I'm uncomfortable using the same symbol to mean two slightly different things. The exclamation point on the tab row means 'this entity has pending revisions', if implemented as described in the variant tags, it would me 'this entity and/or its child evidence items have pending revisions'. I would prefer that symbol to mean the same thing everywhere it appears. We could perhaps use a different color on the symbol to indicate revisions in just the variant and revisions in variant and/or evidence items.

Also, the server query for determining if a variant plus all its evidence items has pending revisions might be potentially far more expensive than just checking the variant - @acoffman, what do you think?

**Comment by malachig** [comment]
That make sense.  

If there is a way to visually distinguish whether the variant itself is under revision or has pending child evidence records in need of attention, that would be awesome.

**Comment by acoffman** [comment]
Its a somewhat expensive query, but not prohibitively so if we structure it correctly. We wouldn't want to do it everyt ime we get a list of variants for a gene in any API call. I think though that we already separate out a call to `check_for_pending_changes` into its own endpoint/query to power some of the existing notices (especially the field specific ones).

If we could have a similar dedicated endpoint that returns "here's all the variants for a gene with outstanding changes" and then that can called when rendering the nav, that would be ideal (and easy to do server side).

**Comment by yanyangfeng** [comment]
So currently just querying the variants with pending revisions (for each variant in variantMenu) using '/api/variants/:variantId/fields_with_pending_changes' crashes the site. 

Could we do something where we just add a numberPendingVariantRevisions and numberPendingEvidenceRevisions value to the variant model, which get updated when a revision is suggested/accepted/rejected? Then for loading varientMenu, we would just need to query for those two values for each variant.

**Comment by susannasiebert** [comment]
I believe this has been implemented. Resolving.
