### ISSUE TITLE
Variants within a gene should be sorted according amino acid or genome coordinate

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-client#67]
Sorting of variants is important to an intuitive display.  For example:

Sorted by position:
L8Q, G12D, V600E 

Is not as intuitive as sorted alphabetically:
G12D, L8Q, V600E

We can wait on fixing this until we have coordinates entered for all variants.  Then we can use chromosome position to accomplish the sorting...

**Comment by jmcmichael** [comment]
I'll just need the sort order sent over from civic-server w/ any endpoint that returns multiple variants. I've created an issue in civic-server, github.com/genome/civic-server#41, for this enhancement.

**Comment by malachig** [comment]
Further refinement of this idea.  Sort should be based on `Variant` `Start` coordinate for all variants where it is defined.  

If `Start` is not defined, these will go at the bottom (sorted by name).

**Comment by kkrysiak** [comment]
Could this get tricky with fusions? Since the second coordinate is for the 3' partner, which is usually the important gene which it should be filed under. I guess a workaround for that would be to prioritize secondary coordinates, when available.

**Comment by malachig** [comment]
Yeah, you are right, fusions would need to be handled as a special case.  This will be hard because sometimes the fusion is entered under the 5' partner and sometimes under the 3' partner.  And which is the case is not recorded in the database...  As long as the name uses official gene names, you could use that to figure it out...  e.g. BCR-ABL1 is entered under ABL1, therefore use the coordinates for the 3' partner.  But that seems a bit clunky.

**Comment by kkrysiak** [comment]
I guess you could look for a match to the mygeneinfo chromosome and pick the coordinates. DNAJB1:PRKACA would be an obvious exception, but for the most part maybe that would work. Or use the secondary coordinate unless the chromosome doesn't match?

**Comment by jmcmichael** [comment]
For this to be implemented on the client, server endpoints returning multiple variants should include a field the client can use for sorting by amino acid or germline coord.

**Comment by arpaddanos** [comment]
Issue of variant sorting also ties into larger issues of variant display and there is user feedback on this to be considered, it seems a V2 issue

**Comment by susannasiebert** [comment]
This is a subissue of https://github.com/griffithlab/civic-client/issues/630

**Comment by susannasiebert** [comment]
This has been implemented
