### ISSUE TITLE
MyVariant.info is giving invalid COSMIC IDs

### ISSUE THREAD

**Issue by KujanL** [griffithlab/civic-client#678]
For EGFR gene, variant E746G, MyVariant.info is giving a COSMIC ID of 1451586. COSMIC says that no such ID exists:
![screen shot 2017-02-03 at 5 04 52 pm](https://cloud.githubusercontent.com/assets/15361912/22611917/ea8310b8-ea32-11e6-8ccb-f95f61d14241.png)

What COSMIC Says:
![screen shot 2017-02-03 at 5 03 46 pm](https://cloud.githubusercontent.com/assets/15361912/22611899/d6048bd0-ea32-11e6-8bd9-8ab1548260d1.png)

**Comment by KujanL** [comment]
I am running into many more variants that are like this. One variant I just ran into with this problem was  gene: PDGFRA/ variant: V561A

![screen shot 2017-02-08 at 3 50 46 pm](https://cloud.githubusercontent.com/assets/15361912/22758986/7349556a-ee16-11e6-82da-59935b673daf.png)
![screen shot 2017-02-08 at 3 50 46 pm](https://cloud.githubusercontent.com/assets/15361912/22758988/750f8fe0-ee16-11e6-9ce9-c9370b9f4065.png)

**Comment by acoffman** [comment]
@KujanL do you know if the other MyVariant.info fields look correct based on the variant? Basically are we matching the correct MyVariant.info record but this particular field is wrong, or are we somehow matching the wrong MyVariant.info record.

**Comment by kkrysiak** [comment]
So the correct COSMIC ID for that variant should be http://cancer.sanger.ac.uk/cosmic/mutation/overview?id=85787 but COSMIC doesn't provide any chromosome stop/start information.

**Comment by acoffman** [comment]
@KujanL, After some digging with help from @kkrysiak, it looks like this is an issue on MyVariant.info's side of things. I've filed an issue with them here: SuLab/myvariant.info#25 so hopefully we can get to the bottom of it!

**Comment by kkrysiak** [comment]
This is a licensing problem. They are using the last version that was made publicly available, I do believe.
