### ISSUE TITLE
Enable active watch/subscribe of CIViC entities (gene, variant)

### ISSUE THREAD

**Issue by obigriffith** [griffithlab/civic-client#683]
I know we have discussed this but can't find an issue for it and would like to revive. It would be great if we could actively watch, subscribe, favorite an entity. A specific use case is if where we have a new expert editor join and they would like to start watching specific gene(s), variant(s) etc. Ideally they could also be notified for more complex sets of events such as all activity related to a specific disease.

**Comment by kkrysiak** [comment]
On that note, the ability to unsubscribe would be nice as well. :) basically just a way to manage subscriptions.

**Comment by susannasiebert** [comment]
This has been resolved.
