### ISSUE TITLE
create method for user to 'flag' first-class entities with serious errors or flawed interpretations

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/civic-client#703]
- flag icon next to edit pencil
- pops up panel w/ comment
- immediately flags entity as problematic by turning flag red or something more obvious
- editors/admins can toggle flag back off after correcting issue

**Comment by susannasiebert** [comment]
I believe this has been implemented, correct? Closing this issues but feel free to reopen if this is still an issue
