### ISSUE TITLE
Add other options to user-submitted Variant ClinVar ID

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#705]
ClinVar IDs at the variant level (entered by user, not myVariant.info) should have 3 options.
- ClinVar ID
- N/A -> not applicable
- None Found.

After discussion with @malachig and Lynzey, this seems like the best option. N/A is used in cases like fusions where ClinVar has no way to represent this. Other variants may be entered at some point into ClinVar but we want to mark variants that were checked and when they were checked, hence, "none found".

**Comment by jmcmichael** [comment]
This should probably be implemented with a select dropdown and the current multi-select component. The multiselect would only be shown if the user chooses the option that indicates that they have one or more clinvar IDs to provide.

**Comment by obigriffith** [comment]
We should also disable ClinVar url construction for the 'None Found' option as was apparently done for 'N/A'. The latter doesn't generate broken links but the former does.

**Comment by kkrysiak** [comment]
We have "None found" and "Not applicable" as the sections. The documentation needs to reflect this.

**Comment by kkrysiak** [comment]
This issue is redundant with https://github.com/griffithlab/civic-client/issues/761. Closing
