### ISSUE TITLE
variants with evidence with outstanding revisions do not show an explanation point

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-client#709]
For example,

https://civic.genome.wustl.edu/#/events/genes/58/summary/variants/849/summary#variant

This variant '19A>G (N7D)' has evidence with pending revisions but does not show an explanation point in the variant list above.

<img width="1259" alt="screen shot 2017-03-13 at 1 14 45 pm" src="https://cloud.githubusercontent.com/assets/856728/23868863/0bfca518-07ef-11e7-8442-c474399d7ff2.png">

It looks like you get an explanation point if there is evidence waiting to be approved/rejected, but not for revisions of the evidence?

**Comment by jmcmichael** [comment]
Yeah, currently the exclamation point only pops up for pending submitted evidence, not submitted changes. I believe that implementing this on the server side requires some work to make the query performant and that @acoffman has plans to do this in the near future.

**Comment by susannasiebert** [comment]
@malachig I believe this has been addressed, correct?
