### ISSUE TITLE
Attribution for group, project, grant etc

### ISSUE THREAD

**Issue by obigriffith** [griffithlab/civic-client#71]
Some contributors, especially bulk contributors are going to want to be able to advertise and give credit to their broader initiative (not just the individual submitter). 

For example we had this feedback from an early user: "I have a large number of annotations that serve as knowledge base for precision medicine trial for the SU2C melanoma dream team. I need to do some checking, but would like to submit them to CIViC, and if they could be attributed to that grant and effort that would be great."

Any ideas how we could handle this?

In ORegAnno we had the concept of a "dataset" where each individual record could be linked to a dataset entry that was associated with some meta-data.

**Comment by acoffman** [comment]
This seems fairly analogous to "sources" in DGIdb. I imagine we can handle something like this fairly easily.

**Comment by jmcmichael** [comment]
I was thinking that provider of a major import could have its own user, with a profile page etc. Then we can just drop that in like a standard 'added by' attribution. More details can go on its user page regarding the institution, specific details about the import, etc.

**Comment by malachig** [comment]
Yeah, this is a good idea.  I think we should also consider allowing users to be part of groups (e.g. 'MGI', 'OHSU', etc.).  Or maybe this is simply an attribute of the user...  It would be good if we could attribute content to both individual users and institutes.  As Obi said we need some way of attributing content not just to users but to institutions, projects, grants, etc.  

Maybe the simplest way to implement this now is to have an 'MGI' users that is assigned for our bulk import and an 'OHSU' user that is assigned for their bulk import, and a 'BCGSC' user assigned for bulk import of the POGS data, etc.

**Comment by kkrysiak** [comment]
Organizations do this. I'll create a new issue to handle grants alone.
