### ISSUE TITLE
would be nice if the Evidence advanced search form's clinical significance options would only show appropriate values based on evidence type

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/civic-client#710]
Currently the clinical significance dropdown provides all ~10 options, even if a evidence type is specified. If evidence type is specified, then it would be possible to limit the clinical significance options to only those possible given the selected evidence type. The logic for handling this might be difficult to accomplish given the design of the query-builder, however.

**Comment by susannasiebert** [comment]
This will be address #905
