### ISSUE TITLE
Consider future integration/support for medical ontologies, controlled vocabularies, or other widely accepted guidelines 

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-client#73]
At AGBT, several parties expressed an interest in CIViC and recommended various resources that might help other entities integrate CIViC into their existing work flows as well as increase practical utility to clinicians down the road.

These included:
- [UML - Unified Medical Language](http://en.wikipedia.org/wiki/Unified_Medical_Language_System)
- [SNOMED - Systematized Nomenclature of Medicine](http://en.wikipedia.org/wiki/Systematized_Nomenclature_of_Medicine)
- [ICD - International Statistical Classification of Diseases and Related Health Problems](http://en.wikipedia.org/wiki/International_Statistical_Classification_of_Diseases_and_Related_Health_Problems)

With regard to cancer specifically we should consider guidelines, etc. from the [National Comprehensive Cancer Network](http://www.nccn.org/).

**Comment by malachig** [comment]
These are primarily relevant in the context of the cancer types.  We use Disease Ontology.  It maps to UML, SNOMED, and ICD.  We can lean on those mappings.

**Comment by jmcmichael** [comment]
We currently map to these via DOID, and will consider integration with other ontologies as it comes up, closing.
