### ISSUE TITLE
Provide links to COSMIC and ClinVar at the gene level

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#738]
Looking through the varsome integration of CIViC, I notice they provide link outs to resources such as COSMIC at the gene level even when looking at the page for a specific variant. I think this would be great to have such a thing at the gene level. Even if we don't have coordinates or anything else for a gene, this would allow us to have a button to take you directly to the ClinVar or COSMIC search for that gene. 

ClinVar is pretty straightforward for their link style. https://www.ncbi.nlm.nih.gov/clinvar/?term=MSH6[gene]

COSMIC is similar (http://cancer.sanger.ac.uk/cosmic/search?q=msh6) for a really basic approach. Ideally, I would like to go straight to the mutation visualization page for the gene (http://cancer.sanger.ac.uk/cosmic/gene/analysis?ln=MSH6). But it's not always so straightforward. Some genes have more than 1 entry (http://cancer.sanger.ac.uk/cosmic/search?q=EZH2) depending on how others provided data. We should also consider whether we would want to redirect to the GRCh37 or 38 site.

**Comment by kkrysiak** [comment]
Perhaps OMIM as well?

**Comment by kkrysiak** [comment]
We should see if these can be shown in the myvariant.info.

**Comment by malachig** [comment]
To avoid adding a lot of complexity to the view and to allow us to accommodate a growing list of link outs to complementary resources I think we should aim for something very compact.  I like the simplicity of the approach used in NCBI.  For example, many pages have a simple "Links" button.  When you hit that a drop down appears with a list of URLs to external sources.  Here is an example screenshot:

![links example](https://cloud.githubusercontent.com/assets/856728/25534502/8c90cce4-2bf9-11e7-8a71-698f08a2e4a0.png)

**Comment by susannasiebert** [comment]
This has been implemented
