### ISSUE TITLE
Variant talk page section titles confused by multi-word variant names

### ISSUE THREAD

**Issue by obigriffith** [griffithlab/civic-client#749]
Something strange seems to be happening on Variant talk pages when we have complex variant names (including spaces). With a typical variant like R1275Q the variant talk page has the expected three sub-sections/tabs (R1275Q Revisions, R1275Q Comments, R1275Q Log). But for a variant like "EML4-ALK AMPLIFICATION" we see the second word being duplicated and the generic section titles absent resulting in all three headings appearing as "EML4-ALK AMPLIFICATION AMPLIFICATION".

![screenshot 2017-05-13 22 21 26](https://cloud.githubusercontent.com/assets/1638042/26031020/0320999c-382b-11e7-91d1-057f9daf5653.png)

**Comment by susannasiebert** [comment]
The fix for #853 might've solved this. @jmcmichael  can you confirm

**Comment by susannasiebert** [comment]
I confirmed that this issue is also closed by #1316
