### ISSUE TITLE
invalid Pubmed ID on source suggestion page

### ISSUE THREAD

**Issue by juheon** [griffithlab/civic-client#780]
On Source Suggestion page, if users input an invalid Pubmed ID, the citation text field shows "--" but you can hit the submit button on the bottom. If you submit a suggestion with an invalid Pubmed ID, the error message says "Error: 500: Internal Server Error". This message might be difficult to understand for users and we can clarify.

There could be two solutions.
1) Inactivate the submit button when the Pubmed ID is invalid
2) Show clarified error message

In my opinion, the second solution is easier to implement and is more intuitive. The problems of the first solutions are
* If we use the "onchange" event, the submit button will be blinking. 
* If we use the "onfocusout" event, the submit button will not be activated if the user's focus is on the Pubmed ID text field. 

To implement the second solution, I need new error code other than 500 that indicates invalid Pubmed ID.

**Comment by jmcmichael** [comment]
This might be the cause of the evidence items linked to the source with no citation ID.
