### ISSUE TITLE
Mouseover on the Clinical Significance doesn't display help text

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/civic-client#782]
On the Evidence Item review screen (below):

<img width="1114" alt="screen shot 2017-06-22 at 11 07 06 am" src="https://user-images.githubusercontent.com/811065/27444155-1979748c-573b-11e7-8d7a-3553c2689e0e.png">

Hovering over the _Positive_ doesn't display the expected help text. Other mouseovers on this page work fine.

**Comment by juheon** [comment]
https://github.com/griffithlab/civic-client/pull/777
