### ISSUE TITLE
Add country field to user profile

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-client#787]
To show international engagement in CIViC it would be great if each user could indicate what country they are from.  I believe we have curators from USA, Canada, Germany, Spain, and Turkey at least.  If we add this field we can start to get a better picture.

@acoffman I assume this will require a minor backend update as well.

**Comment by susannasiebert** [comment]
On the backend this has been implemented as part of https://github.com/griffithlab/civic-server/pull/354

**Comment by jmcmichael** [comment]
client PR #1064 and server PR griffithlab/civic-server#493 will close this issue.
