### ISSUE TITLE
Add Associated Phenotypes field to evidence records

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-client#789]
It has been suggested that we should allow curation of associated phenotypes in addition to diseases.  For example, for many VHL variants the appropriate disease is `Von-Hippel Lindau` but there is value to being to further specific which phenotypes are observed in each patient within this syndrome (e.g. `pheochromocytoma`, `renal cell carcinoma`, `hemangioblastoma of the CNS`, etc.).

It has been suggested that we use [HPO terms](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118) for this purpose similarly to how we use DO terms for the disease.

**Comment by malachig** [comment]
Other alternatives to [HPO](http://compbio.charite.de/hpoweb/showterm?id=HP:0000118), are [UMLS](https://www.nlm.nih.gov/research/umls/) and [SNOMED](https://www.nlm.nih.gov/healthit/snomedct/).  Others we should consider?

- Should we consider supporting more than one in some generic way?
- Are there licensing issues with any of these?

**Comment by malachig** [comment]
On the licensing issue:
- For HPO, I see no problems with how CIViC would use it: http://human-phenotype-ontology.github.io/license.html
- SNOMED and UMLS seem a bit more complicated...

**Comment by malachig** [comment]
Another option that has been recommended to us several times is [NCI Thesaurus](https://ncit.nci.nih.gov/ncitbrowser/pages/home.jsf?version=17.05e).  It is released as [Public Domain open content license](Public domain, open content license).

**Comment by malachig** [comment]
HPO appears to have periodic stable releases:
http://human-phenotype-ontology.github.io/

**Comment by malachig** [comment]
It might be nice to support both HPO and NCI thesaurus.

**Comment by susannasiebert** [comment]
We didn't really get a chance to talk about this future during the meeting. Are phenotypes something we want to add evidence items or to assertions? Or to both?

**Comment by malachig** [comment]
Good question.  I think to both

**Comment by kkrysiak** [comment]
Let's go with HPO for now as well.

**Comment by kkrysiak** [comment]
I think we decided to require an HPO term to first be added using an HPO ID, pulling that from their API. Only HPO IDs that have been added will be in the type ahead search for text. This reduces the crazy number of options in the type ahead search.

**Comment by arpaddanos** [comment]
It looks like we could use these to create EIDs for brain metastases:
http://compbio.charite.de/hpoweb/showterm?id=HP:0030692
 
Choose say NSCLC from DOID and then the above from HPO.

**Comment by kkrysiak** [comment]
When we provide the message that people should identify an HPO term, they should be directed to the following URL. I find the home page non-intuitive and would rather direct them immediately to the term browser that is relevant.
http://www.human-phenotype-ontology.org/hpoweb?id=HP:0000118

@arpaddanos I'm not sure I agree with that approach but we should definitely discuss that in our next CIViC meeting.

**Comment by malachig** [comment]
HPO is now integrated!  Great job all.  Closing this issue.
