### ISSUE TITLE
Deletion of Numbers in the Transcript Name to 'ENST'

### ISSUE THREAD

**Issue by KujanL** [griffithlab/civic-client#798]
When working on the many VHL variants, I noticed that when I use the memory function that my computer has for entries to select the Ensembl transcript the entry is deleted when I submit my revision. But if I manually type in the full transcript name, the name is not deleted when I submit my revision. This has never happened before, and I had always used the memory function, especially when it comes to VHL variants. I didn't see a reason why the entry wouldn't work as well. 

For VHL R107G (c.319C>G):

Memory function:

![screen shot 2017-07-25 at 11 29 36 pm](https://user-images.githubusercontent.com/15361912/28603390-bb5435c4-7191-11e7-9c78-c5a3157eeb59.png)

Pre-Submission:

![screen shot 2017-07-25 at 11 31 01 pm](https://user-images.githubusercontent.com/15361912/28603392-c14e739a-7191-11e7-80c0-cdf3d1ea74b1.png)

Post-Submission:

![screen shot 2017-07-25 at 11 33 06 pm](https://user-images.githubusercontent.com/15361912/28603401-c97dfa54-7191-11e7-9670-3e1f4084b8a9.png)

**Comment by kkrysiak** [comment]
@KujanL, this has been fixed, right? I havne't noticed it in anything recent.
