### ISSUE TITLE
Variant type search is either not working or case-based

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#799]
Excluding "coding" still produces "Coding Sequence Variant"
<img width="1127" alt="screen shot 2017-07-31 at 11 06 56 am" src="https://user-images.githubusercontent.com/8527125/28787165-0a45c7b2-75e1-11e7-986a-581ad7f65248.png">

**Comment by susannasiebert** [comment]
I believe this issue can be closed. @kkrysiak can you confirm that the merged PR on the civic-server fixes this issue?

**Comment by susannasiebert** [comment]
Adam is super fast. Didn't see that he already closed this.
