### ISSUE TITLE
integrate assertions into variant summary view

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/civic-client#801]
Assertions endpoints are now implemented on the server, and need to be added to the UI as first-class entities.

**Comment by malachig** [comment]
Note that as part of assertions we want to support ACMG evidence codes being added to assertions.

These evidence codes are defined in this publication: https://www.ncbi.nlm.nih.gov/pubmed/25741868

Table 3 and Table 4 define the valid evidence codes. The codes are in two groups:
Supporting pathogenicity: `PVS1`, `PS1`, `PS2`, `PS3`, `PS4`, `PM1`, `PM2`, `PM3`, `PM4`, `PM5`, `PM5`, `PP1`, `PP2`, `PP3`, `PP4`, `PP5`.
Supporting benign: `BA`, `BS1`, `BS2`, `BS3`, `BS4`, `BP1`, `BP2`, `BP3`, `BP4`, `BP5`, `BP6`, `BP7`.

Each already has a help text blurb associated with it (from Table 3 & Table 4).

We want the interface to do the following:
1.) Allow you to pick an evidence code from the list of valid options. As you select one, show the help text blurb from the guidelines so the user is reminded what each code is about.
2.) Once selected, force the user to comment on why they are assigning that evidence code.
3.) Allow the user to assign an arbitrary number of these codes, each with a separate comment. 

A future task will be to perhaps automatically calculate whether a combination of ACMG codes adds up to a final designation of `Pathogenic`, `Likely Pathogenic`, `Variant of Uncertain Signification`, `Likely Benign`, or `Benign`.

**Comment by susannasiebert** [comment]
This is done. I will make a separate issue for incorporating the pathogenicity calculator.
