### ISSUE TITLE
Display evidence grid for an organization

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/civic-client#805]
I didn't see an issue for this so feel free to close this one if I missed it.

We discussed adding an evidence grid on each organization's page that shows all the evidence submitted by users in that organization.

**Comment by susannasiebert** [comment]
The server-side changes necessary for this feature have been merged in as part of PR https://github.com/griffithlab/civic-server#353. The new endpoint can be found at `api/organizations/:id/evidence_items`.

**Comment by jmcmichael** [comment]
Done, pushed to master.
