### ISSUE TITLE
create Add Assertion form

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/civic-client#810]
Form should include:
- Gene
- Variant
- Disease
- Variant Origin
- Evidence Type
  - diag
  - predictive
  - predisposing
- ACMG Codes (only specified if evidence type == predisposing)
- Clinical significance (only shown for diagnostic, predictive, prognostic types)
- AMP Level (only shown for diagnostic, predictive, prognostic types)
- evidence items (allow user to filter all, checkbox to select for inclusion)
- Regulatory Approval
  - FDA
  - BFARM
- NCCN Guideline (checkbox)
  - NCCN guideline selector (if checked)
  - NCCN guideline version (freeform text)

Place form in Add section, allow user to easily choose between adding evidence and adding an assertion.

**Comment by kkrysiak** [comment]
Working spreadsheet.
https://docs.google.com/spreadsheets/d/1OP1Uy_P8kKzB_RP5YiuIUR6rtytV8tLnbE8M0FtbiNs/edit#gid=0

**Comment by kkrysiak** [comment]
For FDA approval and FDA companion test. FDA approval is only for predictive assertions. Only show these fields if they are positive, not if they are negative or unknown.

Down side to this is FDA status is not a field a user will know that can obviously be added. Warrants more discussion.

**Comment by kkrysiak** [comment]
Also need to discuss how to handle submitted evidence items. A curator who created the evidence items may want to submit an assertion using them. If we restrict that action than it's dependent upon editors to accept those evidence items and the curator to come back and add them.

**Comment by kkrysiak** [comment]
Add
- Myvariant.info
- Allele registry
- Event stream (like on evidence statements)
- Multiple ACMG codes (eg., PP4 (3) )
- Name of AID (incorrectly ASR above evidence grid)
