### ISSUE TITLE
Flag button active when not signed in

### ISSUE THREAD

**Issue by yang-yangfeng** [griffithlab/civic-client#812]
Didn't want to actually submit the flag since this was on the live site, but it seems like I can flag when I'm not signed in? At the very least, we should disable clicking the flag button.

<img width="1260" alt="screen shot 2017-10-12 at 1 34 53 pm" src="https://user-images.githubusercontent.com/16638655/31512928-376435f8-af52-11e7-9080-64bb1f111008.png">

**Comment by jmcmichael** [comment]
Fixed - 'Flag' button now disabled if user signed out.
