### ISSUE TITLE
Add gnomAD data

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#816]
Myvariant.info now makes gnomAD details available, we should replace the ExAC adj allele freq on the variant pages with them. We can retain the details about ExAC in the myvariant.info details page. Unlike ExAC, there are two sets of data, the exome sequencing results and the whole genome sequencing results.

Shorthand representation is gnomAD Exomes AF or gnomAD Genomes AF. This may be a display issue on the variant page since ExAC Adj. AF is _much_ shorter. I'll add suggestions for alternative ways to handle this.

Related to: https://github.com/griffithlab/civic-server/issues/366

Add to MyVariant.info Details page:
```
The Genome Aggregation Database
Exome Allele Frequency:  'gnomad_exome.af.af'
Exome Allele Count: 'gnomad_exome.ac.ac'
Exome Allele Number: 'gnomad_exome.an.an'
Genome Allele Frequency: 'gnomad_genome.af.af'
Genome Allele Count: 'gnomad_genome.ac.ac'
Genome Allele Number: 'gnomad_genome.an.an'

**Comment by kkrysiak** [comment]
See the server side issue for additional suggestions just so I don't have to retype all this here...

**Comment by jmcmichael** [comment]
Example variants to use for testing MyVariantInfo API responses:

VHL R200W - Both Genomes and Exomes
BRAF V600E - Exomes only
TERT C228T - Genomes only 
VHL S72P - No Genomes and Exomes = 0/228866 alleles

**Comment by kkrysiak** [comment]
If you could add the full length allele frequency instead of the rounded version to the hover text, that would be great.

**Comment by susannasiebert** [comment]
@kkrysiak #831 changes the tooltip to display the full allele frequency without rounding.

**Comment by kkrysiak** [comment]
This has been done.

**Comment by kkrysiak** [comment]
This has been done.
