### ISSUE TITLE
Assertion subscription notifications are not working properly

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#842]
Arpad submitted AID3 yesterday, this is how it appears on my notifications page. Clicking the notification also doesn't link to anything.
<img width="1127" alt="screen shot 2018-01-17 at 10 28 10 am" src="https://user-images.githubusercontent.com/8527125/35054041-56940bb8-fb71-11e7-8408-9b248a401798.png">

**Comment by susannasiebert** [comment]
I believe this is fixed. Please reopen if it's still an issue.
