### ISSUE TITLE
Variant groups are being linked to the wrong pages

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#844]
From the Browse page for Variant Groups if you click on the "EGFR TKI Resistance" group it takes you to the gene ALK. None of the variants in that group are ALK so this navigating to the wrong place.

https://civic.genome.wustl.edu/events/genes/1/summary/variantGroups/12/summary#variant-group

**Comment by susannasiebert** [comment]
This appears to be fixed. @kkrysiak can you confirm?

**Comment by kkrysiak** [comment]
Looks fixed!
