### ISSUE TITLE
Additional my.variantinfo to add

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#851]
To support options that are helpful for evaluating evidence according to ACMG guidelines. Information to add to the my.variantinfo pop up.

Effect predictors (get prediction and score):
- REVEL
- SIFT - (DROP FROM CADD IMPORT)
- Polyphen2 HDIV
- Polyphen2 HVAR
- LRT
- MutationTaster
- MutationAssessor
- FATHMM
- PROVEAN
- MetaSVM
- MetaLR
- CADD - (ALREADY COVERED IN A SEPARATE FIELD)
- FATHMM-MKL
- fitCons (integrated indicates integrated across all 4 cell types scored)

dbnsnfp subset of data:
dbnsfp.revel.score
dbnsfp.sift.pred
dbnsfp.sift.score
dbnsfp.polyphen2.hdiv.pred
dbnsfp.polyphen2.hdiv.score
dbnsfp.polyphen2.hvar.pred
dbnsfp.polyphen2.hvar.score
dbnsfp.lrt.pred
dbnsfp.lrt.score
dbnsfp.mutationtaster.pred
dbnsfp.mutationtaster.score
dbnsfp.mutationassessor.pred
dbnsfp.mutationassessor.score
dbnsfp.fathmm.pred
dbnsfp.fathmm.score
dbnsfp.provean.pred
dbnsfp.provean.score
dbnsfp.metasvm.pred
dbnsfp.metasvm.score
dbnsfp.metalr.pred
dbnsfp.metalr.score
dbnsfp.fathmm-mkl.coding_pred
dbnsfp.fathmm-mkl.coding_score
dbnsfp.integrated.fitcons_score

**Comment by kkrysiak** [comment]
CADD version is 0.5 for myvariant info...as of 2015 they were on 1.3 so the data there is definitely behind. Prefer dbnsfp whenever possible.

Consider adding CADD field:
cadd.rawscore

Conservation analysis tools:
- phyloP100way (vertebrate)
- phyloP20way (mammalian)
- phastCons100way (vertebrate)
- phastCons20way (mammalian)
- GERP++ (RS score, not neutral rate[NR])
- SiPhy

dbnsfp sections:
dbnsfp.phylo.p100way.vertebrate
dbnsfp.phylo.p20way.mammalian
dbnsfp.phastcons.100way.vertebrate
dbnsfp.phastcons.20way.mammalian
dbnsfp.gerp++.rs
dbnsfp.siphy_29way.logodds

**Comment by malachig** [comment]
Fantastic job identifying all these.  We should make note of things that we would want and are missing or things that are getting to be outdated and provide this feedback to the myvariant.info.
