### ISSUE TITLE
Incorporate Tiers into AMP Level/categorization?

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/civic-client#855]
DebIrene observed, in a [civicdb.org comment thread](https://civic.genome.wustl.edu/events/assertions/3/talk/comments):

> For assertions, I wouldn’t strip the “Tier” part of the AMP categorization. Currently it says “AMP Level” and then “A.”
> 
> But it should be something like “AMP Categorization” and then “Tier I , Level A” or “IA” or “1A” – something to include the Tier number.
> 
> They may in the future revise and add something else to the schema, who knows, Tier 1 may include A B and E for example.
> 
> Also keeping Tiers for I and II makes more sense for the letter-less Tiers III (uncertain) and IV (benign), because those technically have no “level”.
> 
> Small comment but wanted to make it now while language/terms are not set in stone with a small number of assertions at this point.

This issue is to discuss the suggestion to incorporate AMP tiers into CIViC assertions.

**Comment by arpaddanos** [comment]
Thinking some more about this one sees Tier is actually forced to be taken within clinical context and not purely associated with a variant. A single variant can have different Tiers in different disease contexts. Take HER2. It is clearly a Tier One variant in breast cancer. But it is also associated with Level C evidence (FDA-approved therapies for different tumor types or investigational therapies) in say Salivary Gland cancer where it has been targeted but is not Tier I (Level A FDA-approved or Level B well-powered studies). So in breast cancer HER2 overexpression is a Tier I variant, but in salivary cancer HER2 overexpression is a Tier II variant. 

So the figure with Tiers and Levels above actually *forces* you to make Tier a disease context specific entitiy

**Comment by susannasiebert** [comment]
This has been completed.
