### ISSUE TITLE
Add suggested revisions advanced search page

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#864]
Create a new tab in the advanced search page.

Suggested functionality:
Suggested change entity: Gene, Variant, Assertion, Evidence item
Specific gene/variant/evidence item/assertion filtering by....name, id
Suggested change submitter ID/name
date of revision

Start by all fields shared by suggested changes regardless of entity type.

**Comment by jmcmichael** [comment]
Done!

**Comment by jmcmichael** [comment]
Oops, wrong issue...

**Comment by susannasiebert** [comment]
@jmcmichael I need to hand this off to you. https://github.com/griffithlab/civic-client/pull/1011 implements the basic search form but it's missing the results table at the bottom. It's also not showing up as a new advanced search tab.
