### ISSUE TITLE
Add link to AID to evidence statements

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#868]
We should somehow note that an evidence item is used in an assertion on that EID somewhere.

**Comment by jmcmichael** [comment]
This would require an additional attribute on evidence detail endpoint responses, like 'supported_assertions': [123,543,345] - @susannasiebert, would that be quick to add?

**Comment by susannasiebert** [comment]
I think so. I'll work on it when I get a free minute.

**Comment by susannasiebert** [comment]
PR is here: https://github.com/griffithlab/civic-server/pull/419

**Comment by jmcmichael** [comment]
Latest commits to PR griffithlab/civic-client/pull/875 includes this improvement, closing.

**Comment by jmcmichael** [comment]
![screen shot 2018-03-14 at 3 55 36 pm](https://user-images.githubusercontent.com/132909/37430463-2c73af5e-27a0-11e8-806e-1821e4dfb225.png)
