### ISSUE TITLE
Evidence card sorting

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#869]
Is there a way to control how the evidence items are sorted for the "evidence card" tab in assertions? It would be great if a user could toggle a couple of options. If that is not possible, a more sensible sorting system would be nice (evidence level then star rating).

**Comment by jmcmichael** [comment]
Yeah I can add a 'Sort by:' dropdown with a few options including evidence level and rating.

**Comment by jmcmichael** [comment]
Implemented in PR griffithlab/civic-client/pull/875, closing.
