### ISSUE TITLE
Variant Advanced search  for suggested revisions is broken

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#873]
If you change the number of revisions, it alters other fields.
<img width="802" alt="screen shot 2018-03-10 at 4 24 43 pm" src="https://user-images.githubusercontent.com/8527125/37247388-a54bfb80-247f-11e8-827c-0ffa21c1336f.png">

**Comment by jmcmichael** [comment]
Fixed in PR griffithlab/civic-client/pull/874
