### ISSUE TITLE
Consider renaming variant origin labels to better harmonize with ACMG recommendations

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/civic-client#877]
Original comment from @malachig 

The ACMG guidelines argue against use of the terms "mutation" and polymorphism. To be more consistent with these guidelines we could rename our Variant Origin values as follows:

Somatic mutation -> Somatic
Germline mutation -> Rare germline
Germline polymorphism -> Common germline
Unknown -> Unknown
N/A -> N/A

The help text should have some guidelines as to what constitute 'Common' and 'Rare'.

**Comment by susannasiebert** [comment]
This would involve renaming the enums on the server in app/const/constants.rb, reaming the options where they appear on the client, and renaming them in the help docs.

**Comment by malachig** [comment]
This tagged as being needed for the update paper but I also want to note that this was also needed for the SOP paper.
