### ISSUE TITLE
activity grid does not show AID in Items column

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/civic-client#881]
For Assertion rows, the AID is missing from the Item column.

**Comment by arpaddanos** [comment]
<img width="860" alt="aid_activity" src="https://user-images.githubusercontent.com/13948978/48224351-1778ef80-e35f-11e8-912d-9856e457904f.png">

**Comment by jmcmichael** [comment]
Originally this was accepted behavior - if the subject of the action was not an evidence item, this column was blank. I order to fill this column for every entity, I had the idea of assigning an 'entity id' to every entity, similarly to evidence items: entity_id for genes is 'GID' plus their CIViC ID, variant get 'VID' and so on. If we want Assertion IDs to show up, I think we need to create these IDs for all primary entities.

This is what it looks like:

![screenshot 2019-01-30 13 55 10](https://user-images.githubusercontent.com/132909/52008799-0f7ca780-2497-11e9-960a-6c1166e0ef0e.png)

**Comment by jmcmichael** [comment]
(I've since changed the column name from 'Entity' to 'Entity ID')

**Comment by jmcmichael** [comment]
Done.
