### ISSUE TITLE
Adopt the MVLD approved terms for Clinical Significance of Predictive Evidence

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-client#882]
We should also keep our current extra term "Adverse Response".

Since we already have many predictive evidence statements I propose the following mapping.  If someone decides that an existing "Resistance or Non-Response" entry should be something other than "Resistance" they will need to propose that as a revision.

New terms (old terms that should be migrated to this term):

Resistant (Resistance or Non-Response)
Responsive
Not-Responsive
Sensitive (Sensitivity)
Reduced-Sensitivity
Adverse Response (Adverse Response)
N/A (N/A)

**Comment by arpaddanos** [comment]
The MVLD paper references Dienstmann when discussing the *Effect* field terms:

Dienstmann R, Dong F, Borger D, Dias-Santagata D, Ellisen LW, Le LP, Iafrate AJ. Standardized decision support in next generation sequencing reports of somatic cancer variants. Mol Oncol. 2014;8(5):859–73.

**Comment by susannasiebert** [comment]
We will need a short, one sentence description of these terms, which will show up as the help text when picking one of the options during evidence item creation/editing.

**Comment by susannasiebert** [comment]
This also requires the creation of new icons that are used in the grids (e.g., browse).

**Comment by arpaddanos** [comment]
![3 1](https://user-images.githubusercontent.com/13948978/39890760-5ace5848-5461-11e8-828e-8a5b20fa3a63.jpg)

**Comment by arpaddanos** [comment]
Figure 3a outlines the changes made to the CIViC fields. Figure 3b shows how these updated fields will be mapped to the Dienstmann terms outlined in the reference added above.

**Comment by arpaddanos** [comment]
It looks like only one new icon will be needed.

**Comment by arpaddanos** [comment]
__Sensitivity/Response__: Associated with a clinical or preclinical response to treatment
__Resistance__: Associated with clinical or perclinical treatment resistance to treatment
__Adverse Response__: Associated with an adverse response to drug treatment
__Reduced Sensitivity__: Response to treatment is lower than seen in other treatment contexts

**Comment by susannasiebert** [comment]
@arpaddanos @malachig do we want to change the terms Sensitivity and Resistance to match the MLVD terms (Sensitive, Resistant).

**Comment by malachig** [comment]
I suppose so yeah.

**Comment by malachig** [comment]
okay lets stick with what was in the Human Mutation submission then

**Comment by ahwagner** [comment]
These changes have been pushed to production. Resolving issue.
