### ISSUE TITLE
uBlock prevents search box from working on Chrome

### ISSUE THREAD

**Issue by chrisamiller** [griffithlab/civic-client#885]
If I go to https://civicdb.org, type something in the search field, and then hit enter, a) I don't get the expected dropdown with suggestions and b) it just clears the box and doesn't do any search.  Disabling uBlock Origin extension resolves the problem.  

I realize that this is technically a problem on my end, but lots of other people use adblockers, and if there's a workaround, it'd probably be best if they didn't encounter this frustration first thing.

**Comment by jmcmichael** [comment]
That's interesting, I also use uBlock origin and it appears to work for me OK. We did have an issue a long time ago with uBlock causing problems, which we worked around by renaming an unfortunately-titled library. So it's certainly possible that a recent change in library CDNs could have tripped uBlock's blocking.

Could you please see if you're getting any useful error messages in the browser console? Also what version of uBlock Origin are you using? Just want to make sure we're using the same one.

**Comment by jmcmichael** [comment]
I haven't been able to reproduce this with uBlock or NoScript, where I have all google analytics/tag servers blocked. Closing.
