### ISSUE TITLE
More intuitive main search box

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#886]
The first quick fix I would suggest is change the text inside the search box from "Go to Genes & Variants" to "Go to Genes or Variants". The gene/variant combination does not come up. 

Perhaps a next change would be to do a concatenated version of the gene and variant. Basically, EGFR T790M should bring up that variant in the type ahead. This came from suggestions from a user.

> But, “Go to Genes and Variants” search box seems not to be well functioning very well. I don’t use this search box.
>
> For example, if I enter “EGFR T790M” in “Go to Genes and Variants” box, it will not show the expected search results, unfortunately.
>
> I know that information about “EGFR T790M” could be searched from "Browse" page, but for CIViC beginner, it is not easy to find better search method.
>
> I suggest that you emphasize "Browse" button and "Search" button rather than "Go to Genes and Variants” search box.

**Comment by susannasiebert** [comment]
This has been superseded by #963
