### ISSUE TITLE
Display bug with multiple assertions

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#888]
AID5 and AID6 are on top of each other. Zooming in or out did not change this behavoir.
![screen shot 2018-03-29 at 5 30 04 pm](https://user-images.githubusercontent.com/8527125/38116702-dfbde160-3376-11e8-857d-f22c626034e2.png)

**Comment by jmcmichael** [comment]
Fixed this awhile ago, closing.

![screenshot 2019-01-30 14 23 08](https://user-images.githubusercontent.com/132909/52010220-997a3f80-249a-11e9-8038-7c52435834d8.png)
