### ISSUE TITLE
Can't add new DOID to record.

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#889]
Per our request, chronic neutrophilic leukemia was added to disease-ontology. https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/280#issuecomment-315180267
Shown here: http://www.disease-ontology.org/?id=DOID:0080187

However, I still can't update this evidence item.
https://civicdb.org/events/genes/1239/summary/variants/560/summary/evidence/1388/summary#evidence

I assume it's missing from the DOID file.

**Comment by kkrysiak** [comment]
I just confirmed, these are missing from the cancer subset file. https://github.com/DiseaseOntology/HumanDiseaseOntology/tree/master/src/ontology/subsets

This is a good argument to use a combination search, prioritizing things already in CIViC or in the cancer DO file and if not found, searching the remainder of DO.

**Comment by susannasiebert** [comment]
This appears to have been added to the cancer subset. @kkrysiak can you confirm that you can update the EID?

**Comment by kkrysiak** [comment]
I can’t currently update it. I believe because there are duplicated entries (one with and one without a DOID associated). It claims to be working but no suggested changes are submitted. When we update like this, we should supersede the existing entry with the one that has a DOID. In this case the names are identical. 

This also makes me think that we should have entities that aren’t in Disease ontology somehow not linkable. Maybe hover text saying not in disease ontology. I don’t find it linking to the main DO page terribly helpful.

**Comment by susannasiebert** [comment]
I think we should have the scraper also update existing entries to link new doids.

**Comment by susannasiebert** [comment]
I updated the the existing disease entry with the doid, deleted the duplicate one, and made a PR to update the job that imports DO entities to check the database for existing diseases with the same name before creating a new entry (PR https://github.com/griffithlab/civic-server/pull/481).
