### ISSUE TITLE
Make funding acknowledgements much more prominent

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-client#896]
Currently we just have some text here: https://civicdb.org/about#acknowledgements

We should acknowledge our funders more prominently: NCI (U01), NHGRI (K99/R00), and ICTS (NCATS CTSA Grant UL1 TR002345).

I will update the text at the location mentioned above, but we brand more prominently.  Perhaps we should have additional logos along the footer of each page.  Right now we are using that space to acknowledge our institute (who helps with hosting and other support), GA4GH (guidance on standards development and adoption).  The funders giving the most support are getting short changed here.

**Comment by susannasiebert** [comment]
This has been released in production. Resolving.
