### ISSUE TITLE
Add a variant type filter to the gene variant list

### ISSUE THREAD

**Issue by KujanL** [griffithlab/civic-client#898]
Some genes have MANY variants, and the when looking at the list, it looks quite crowded. For genes that have this many variants, it might be better to organize by variant type - for example there are tabs for the variant types and when selected all the variants under that variant type are listed. 
![screen shot 2018-04-28 at 9 56 57 pm](https://user-images.githubusercontent.com/15361912/39402773-215213b0-4b2f-11e8-98cb-e993d9398845.png)
![screen shot 2018-04-28 at 9 57 06 pm](https://user-images.githubusercontent.com/15361912/39402774-24120c68-4b2f-11e8-9e16-399bd1de9f45.png)

I know for genes like VHL, missense variants are still going to be abundant and a variant type tab will probably not be a good solution. 

I just wanted to get the conversation started, and see if there are any other possible solutions!:)

**Comment by kkrysiak** [comment]
I know with the website redesign for v2 this will be handled differently. But I wonder if adding the variant type to the filter variants feature might be a nice, interim solution? Or were you thinking of having multiple tabs?

**Comment by KujanL** [comment]
I think a filter might work as an interim solution! I just think that a user will be overwhelmed and confused on where to find a specific variant within a crowded gene, such as VHL.

**Comment by susannasiebert** [comment]
We've added some more filtering options to the variants list. You can toggle them by clicking the "Display Options" button. I'm resolving this issue.
