### ISSUE TITLE
sorting of evidence and assertion browse views

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-client#908]
I feel like the browse evidence view used to be sorted?

https://civicdb.org/browse/assertions
https://civicdb.org/browse/evidence

Currently they are sorted only by EID or AID.

A good sorting for evidence could be: EL -> TR -> ET. 

A good sorting for assertions could be evidence count.

**Comment by susannasiebert** [comment]
I don't believe it's possible to do a nested sorting like you're suggesting for evidence items. Do you have a preference for a single field to sort by?

**Comment by susannasiebert** [comment]
I stand correct. Josh pointed out that nested sorting is in fact possible. I'm working on that now.
