### ISSUE TITLE
Commenting is buried a little deep

### ISSUE THREAD

**Issue by obigriffith** [griffithlab/civic-client#91]
If I want to make an edit to an entity (gene, variant, evidence) there is a direct edit button. But, to simply leave a comment, I need to go to the entity Talk page page, then to the Comments tab. If there are existing comments it is not super obvious that the empty Title/Comment boxes are for entering a new comment. There should maybe be comment button similar to edit button next to each entity. And, the comment section should have a heading that says something like: Please add a comment with the form below!

**Comment by jmcmichael** [comment]
Yeah, I agree. Adding a subtle button in the header next to the title that links directly to the comments view sounds like a decent fix. Regarding the comment form layout, I'm going to copy the chat/comment style closer to the one we're using with github right now, and eliminate the title field.

**Comment by kkrysiak** [comment]
bump

**Comment by kkrysiak** [comment]
Close in favor of #802
