### ISSUE TITLE
Cancel button for add assertion form

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-client#911]
On the add evidence form you can cancel out.  This is very handy for showing the site to new users.  Would be great to have a cancel button on Add Assertion form.

**Comment by obigriffith** [comment]
Has this not happened? Still a source of annoyance for editors. Since this functionality does exist on edit assertion maybe it is a quick fix?

**Comment by jmcmichael** [comment]
Yeah this should be easy to add, I've added it to my queue of issues to tackle after this papers/figures sprint.
