### ISSUE TITLE
comma/spacing issue for HGVS expressions

### ISSUE THREAD

**Issue by obigriffith** [griffithlab/civic-client#915]
Note, each HGVS expression is followed by a space and then comma. 

Also, for both HGVS expressions and Variant aliases I think we should drop the "and".

**Comment by obigriffith** [comment]
<img width="1146" alt="screenshot 2018-06-05 10 57 18" src="https://user-images.githubusercontent.com/1638042/40988383-89a80e3a-68b0-11e8-961d-30877854937a.png">

**Comment by susannasiebert** [comment]
We have a similar display logic for variant type and clinvar ID. Do you want to replace the `and` there as well (for multiples)?
