### ISSUE TITLE
Introduce new evidence type - Biological

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#928]
From the grant we proposed the following Clinical Significance options:
- Loss of Function
- Gain of Function
- Neomorphic
- Unaltered Function
- Other

**Comment by kkrysiak** [comment]
Question remains whether we should harmonize these with similar ideas on other resources. In oncoKB this would map as follows:
- Loss of Function - *Loss-of-function / Likely Loss-of-function*
- Gain of Function - *Gain-of-function / Likely Gain-of-function*
- Neomorphic Function - *Switch-of-function / Likely Switch-of-function*
- Unaltered Function - *Neutral*
- Other - *Inconclusive*

**Comment by susannasiebert** [comment]
- Gain of Function
- Loss of Function
- Neomorphic
- Unaltered Function
- Unknown

Basically, we're renaming Other to Unknown.
