### ISSUE TITLE
Integration with NDEX (an ITCR project)

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-client#934]
Rudi from NDEX created an official CIViC account on the NDEx public server (http://ndexbio.org).
 
Rudi will load the 4 “flavors” of the full clinical evidence summaries: this is done in part, 2 networks are available so far.

NDEX has requested the following two modifications to our output files.  By creating new files? 
- CIViC to output and send me a TSV file with an additional column called “gene-variant” that includes both the gene symbol and the variant name (i.e. BRAF-V600E). I need this to load the “variant-disease” and “variant-drug” networks
- CIViC to output the Tab-delimited files, with a “.txt” extension

Apparently the ultimate monthly deploy process to NDEX will involve us running a python script. Perhaps we can just incorporate these needs into that?

**Comment by malachig** [comment]
I believe this is close to done.  We have been provided with a Python script to automate updates.  They would also like us to draw attention to this integration in a news item.

**Comment by susannasiebert** [comment]
Link to script is here: https://github.com/ndexbio/civic-loader
