### ISSUE TITLE
Entries in Talk/Log tab should link to relevant entry in Talk/Comment or Talk/Revision

### ISSUE THREAD

**Issue by obigriffith** [griffithlab/civic-client#94]
When look at a talk page for gene, variant, or evidence the default view is the log listing recent comments and revisions. If I see an interesting comment/revision I need to realize that there are two other tabs corresponding to these kinds of entitites, go to that tab and then find the relevant comment/revision to get more details. The brief entry on the log tab should be a clickable link that takes you to the correct place in the corresponding other tab.

**Comment by jmcmichael** [comment]
This will be solved with implementation of #802
