### ISSUE TITLE
move documentation to ReadTheDocs

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/civic-client#971]
In an effort to move non-core application features/pages from the client codebase and UI, we're moving all the docs to ReadTheDocs at the URL http://civic.readthedocs.io/

This will also allow easier updating of the documentation outside the civic client release schedule.

**Comment by kkrysiak** [comment]
Google doc to organize authorship and work on this. https://docs.google.com/spreadsheets/d/1CXJXsibl3LkHW9gjnkMdnsPai-R6pmX3EYtPInRRHUU/edit#gid=0

**Comment by jmcmichael** [comment]
Done!
